{
 "title": "FinOps Idle Resources",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "thanos", "query": "prometheus" },
   { "name": "athena", "query": "grafana-athena-datasource" }
  ]
 },
 "panels": [
  {
   "title": "AWS Idle EIPs",
   "type": "table",
   "description": "Idle Elastic IPs aggregated by region",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (region) (aws_idle_eip)",
     "legendFormat": "__auto"
    },
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT\r\n  product_region AS region,\r\n  SUM(CAST(line_item_blended_cost AS double)) AS monthly_cost\r\nFROM \"athenacurcfn_finops\".\"finops\"\r\nWHERE\r\n  year = '2026'\r\n  AND product_product_name = 'Amazon Virtual Private Cloud'\r\n  AND line_item_usage_type LIKE '%PublicIPv4:IdleAddress%'\r\nGROUP BY product_region\r\nORDER BY monthly_cost DESC;\r\n"
    }
   ]
  },
  {
   "title": "AWS Idle EBS Volumes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "aws_idle_ebs_volume == 1", "legendFormat": "__auto" },
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT\r\n  line_item_resource_id   AS volume_id,\r\n  SUM(line_item_blended_cost) AS monthly_cost\r\nFROM \"athenacurcfn_finops\".\"finops\"\r\nWHERE\r\n  year = '2026'\r\n  AND line_item_resource_id LIKE 'vol-%'\r\n  AND line_item_line_item_type = 'Usage'\r\nGROUP BY line_item_resource_id\r\nHAVING SUM(line_item_blended_cost) > 0\r\nORDER BY monthly_cost DESC;\r\n"
    }
   ]
  },
  {
   "title": "AWS Idle NAT Gateways",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "aws_idle_nat_gateway", "legendFormat": "__auto" },
    {
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT\n  regexp_extract(\n    line_item_resource_id,\n    'natgateway/(nat-[a-z0-9]+)',\n    1\n  ) AS nat_id,\n  SUM(CAST(line_item_blended_cost AS double)) AS monthly_cost\nFROM \"athenacurcfn_finops\".\"finops\"\nWHERE\n  year = '2026'\n  AND product_product_name = 'Amazon Elastic Compute Cloud'\n  AND (\n        line_item_usage_type LIKE '%NatGateway-Hours%'\n        OR line_item_usage_type LIKE '%NatGateway-Bytes%'\n      )\nGROUP BY\n  regexp_extract(\n    line_item_resource_id,\n    'natgateway/(nat-[a-z0-9]+)',\n    1\n  )\nHAVING SUM(CAST(line_item_blended_cost AS double)) > 0\nORDER BY monthly_cost DESC;"
    }
   ]
  }
 ]
}