{
 "title": "Linux Dashboard",
 "tags": [ "linux" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "client",
    "label": "Account",
    "query": {
     "query": "label_values(node_uname_info,client)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info{client=\"$client\"},job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{client=\"$client\", job=\"$job\"},instance_name)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Instance Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "((1 - (1 - avg(rate(node_cpu_seconds_total{client=\"$client\",job=\"$job\", mode=\"idle\"}[$__rate_interval])) by (instance_name)) ^ 1.3) ^ (1/3) * 0.5 + \n( 1 - (1 - avg(node_memory_MemAvailable_bytes{client=\"$client\",job=\"$job\"} / node_memory_MemTotal_bytes{job=\"$job\"}) by (instance_name)) ^ 6) ^ (1/3) * 0.3 + \n(1 - max(rate(node_disk_io_time_seconds_total{client=\"$client\",job=\"$job\"}[$__rate_interval]))by (instance_name) ^ 1.1) ^ (1/2) * 0.2) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemTotal_bytes{client=\"$client\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{client=\"$client\",job=\"$job\"} / (node_memory_MemTotal_bytes{client=\"$client\",job=\"$job\"}))) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "clamp_min((1 - avg(rate(node_cpu_seconds_total{client=\"$client\",job=\"$job\", mode=\"idle\"}[$__rate_interval])) by (instance_name)) * 100, 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(node_filesystem_avail_bytes{client=\"$client\",job=\"$job\"}) by (instance_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{client=\"$client\",job=\"$job\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval]) * 8) by (instance_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(irate(node_network_receive_bytes_total{client=\"$client\",job=\"$job\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval]) * 8) by (instance_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{client=\"$client\",job=\"$job\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{client=\"$client\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{client=\"$client\",job=\"$job\"}) by (instance_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Traffic Usage (Approx.)",
   "type": "timeseries",
   "description": "This metric provides relatively accurate results within 6-hour period.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{client=\"$client\",job=\"$job\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval])) * 10",
     "legendFormat": "{{instance_name}}Upload"
    },
    {
     "expr": "sum(irate(node_network_receive_bytes_total{client=\"$client\",job=\"$job\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval])) * 10",
     "legendFormat": "{{instance_name}}Download"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{client=\"$client\",job=\"$job\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval]) + irate(node_network_receive_bytes_total{client=\"$client\",job=\"$job\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval])) * 10",
     "legendFormat": "{{instance_name}}Total"
    }
   ]
  },
  {
   "title": "^ ^",
   "type": "stat",
   "description": "Last modified: 23:58, December 3, 2024",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{client=\"$client\",job=\"$job\"} == 1)",
     "legendFormat": "Active Instance(s)"
    },
    {
     "expr": "sum(node_netstat_Tcp_CurrEstab{client=\"$client\",job=\"$job\"})",
     "legendFormat": "All Connections"
    },
    {
     "expr": "(sum(irate(node_network_receive_bytes_total{client=\"$client\",job=\"$job\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval]) + irate(node_network_transmit_bytes_total{client=\"$client\",job=\"$job\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval]))) * 8",
     "legendFormat": "Total Throughput"
    }
   ]
  },
  {
   "title": "Aggregate System Load [5m]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load5{client=\"$client\",job=\"$job\"}",
     "legendFormat": "{{instance_name}}"
    },
    { "expr": "1", "legendFormat": "baseline" }
   ]
  },
  {
   "type": "histogram",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{client=\"$client\",job=\"$job\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval]) * 8 + irate(node_network_receive_bytes_total{client=\"$client\",job=\"$job\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval]) * 8",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Aggregate Transmit Bandwidth Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{client=\"$client\",job=\"$job\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval]) * 8",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Overall Established & TIME_WAIT Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_netstat_Tcp_CurrEstab{client=\"$client\",job=\"$job\"})",
     "legendFormat": "{{instance_name}}Current Established"
    },
    {
     "expr": "sum(node_sockstat_TCP_tw{client=\"$client\",job=\"$job\"})",
     "legendFormat": "{{instance_name}}TIME_WAIT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{client=\"$client\",job=\"$job\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d]))",
     "legendFormat": "Transmit Bandwidth"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{client=\"$client\",job=\"$job\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d]))",
     "legendFormat": "Receive Bandwidth"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{client=\"$client\",job=\"$job\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d])) + sum(increase(node_network_receive_bytes_total{client=\"$client\",job=\"$job\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d]))",
     "legendFormat": "30-Day Bandwidth"
    }
   ]
  },
  { "title": "〔NODE INFO〕↘️ $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{client=\"$client\",job=\"$job\", instance_name=\"$node\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{client=\"$client\",job=\"$job\", instance_name=\"$node\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{client=\"$client\",job=\"$job\", instance_name=\"$node\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d])) + sum(increase(node_network_receive_bytes_total{client=\"$client\",job=\"$job\", instance_name=\"$node\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Average System Load: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{client=\"$client\",job=\"$job\", instance_name=\"$node\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{client=\"$client\",job=\"$job\", instance_name=\"$node\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{client=\"$client\",job=\"$job\", instance_name=\"$node\"}",
     "legendFormat": "15m"
    },
    {
     "expr": "count(node_cpu_seconds_total{client=\"$client\",job=\"$job\", instance_name=\"$node\", mode='system'}) by (instance_name)",
     "legendFormat": "CPU Cores"
    }
   ]
  },
  {
   "title": "Disk Space Usage: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{client=\"$client\",job=\"$job\", instance_name=\"$node\",device!~'rootfs'} - node_filesystem_avail_bytes{client=\"$client\",job=\"$job\", instance_name=\"$node\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Memory Usage: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{client=\"$client\",instance_name=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{client=\"$client\",instance_name=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{client=\"$client\",instance_name=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{client=\"$client\",instance_name=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{client=\"$client\",instance_name=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance_name=\"$node\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{client=\"$client\",instance_name=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{client=\"$client\",instance_name=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{client=\"$client\",instance_name=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{client=\"$client\",instance_name=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{client=\"$client\",instance_name=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{client=\"$client\",instance_name=\"$node\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "CPU Activity Analysis: $node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - (sum(irate(node_cpu_seconds_total{client=\"$client\",instance_name=\"$node\",job=\"$job\",mode=\"idle\"}[$__rate_interval]))  / scalar(count(count(node_cpu_seconds_total{client=\"$client\",instance_name=\"$node\",job=\"$job\"}) by (cpu)))\r\n))\r\n",
     "legendFormat": "CPU Used %"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{client=\"$client\",instance_name=\"$node\",job=\"$job\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{client=\"$client\",instance_name=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{client=\"$client\",instance_name=\"$node\",job=\"$job\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{client=\"$client\",instance_name=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{client=\"$client\",instance_name=\"$node\",job=\"$job\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{client=\"$client\",instance_name=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{client=\"$client\",instance_name=\"$node\",job=\"$job\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{client=\"$client\",instance_name=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{client=\"$client\",job=\"$job\", instance_name=\"$node\"})",
     "legendFormat": "⏱️ Uptime"
    },
    {
     "expr": "count(node_cpu_seconds_total{client=\"$client\",job=\"$job\", instance_name=\"$node\", mode='system'})",
     "legendFormat": "💎 Core(s)"
    },
    {
     "expr": "max(node_filesystem_size_bytes{client=\"$client\",job=\"$job\", instance_name=\"$node\"})",
     "legendFormat": "💾 Disk Size"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{client=\"$client\",job=\"$job\", instance_name=\"$node\"})",
     "legendFormat": "🫙 Memory Total"
    }
   ]
  },
  {
   "title": "Disk Read/Write Rate: $node",
   "type": "timeseries",
   "description": "Read + / Write -",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{client=\"$client\",job=\"$job\", instance_name=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{client=\"$client\",job=\"$job\", instance_name=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Partition Status: $node",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{client=\"$client\",job=\"$job\", instance_name=\"$node\", fstype=~\"ext.*|xfs|nfs\", mountpoint !~\".*pod.*\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_avail_bytes{client=\"$client\",job=\"$job\", instance_name=\"$node\", fstype=~\"ext.*|xfs|nfs\", mountpoint !~\".*pod.*\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_filesystem_size_bytes{client=\"$client\",job=\"$job\", instance_name=\"$node\", fstype=~\"ext.*|xfs|nfs\", mountpoint !~\".*pod.*\"} \n- node_filesystem_free_bytes{client=\"$client\",job=\"$job\", instance_name=\"$node\", fstype=~\"ext.*|xfs|nfs\", mountpoint !~\".*pod.*\"})\n* 100 / node_filesystem_size_bytes{client=\"$client\",job=\"$job\", instance_name=\"$node\", fstype=~\"ext.*|xfs|nfs\", mountpoint !~\".*pod.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Socket: $node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{client=\"$client\",job=\"$job\", instance_name=\"$node\"}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{client=\"$client\",job=\"$job\", instance_name=\"$node\"}[$__rate_interval])",
     "legendFormat": "Tcp_RetransSegs"
    },
    {
     "expr": "node_sockstat_sockets_used{client=\"$client\",job=\"$job\", instance_name=\"$node\"}",
     "legendFormat": "sockets_used"
    },
    {
     "expr": "irate(node_netstat_Tcp_InSegs{client=\"$client\",job=\"$job\", instance_name=\"$node\"}[$__rate_interval])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{client=\"$client\",job=\"$job\", instance_name=\"$node\"}[$__rate_interval])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "node_sockstat_TCP_tw{client=\"$client\",job=\"$job\", instance_name=\"$node\"}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenDrops{client=\"$client\",job=\"$job\", instance_name=\"$node\"}[$__rate_interval])",
     "legendFormat": "TcpExt_ListenDrops"
    },
    {
     "expr": "node_sockstat_UDP_inuse{client=\"$client\",job=\"$job\", instance_name=\"$node\"}",
     "legendFormat": "UDP_inuse"
    }
   ]
  },
  {
   "title": "Network Bandwidth Usage: $node",
   "type": "timeseries",
   "description": "Receive + / Transmit -",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{client=\"$client\",job=\"$job\", instance_name=\"$node\"}[$__rate_interval]) * 8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{client=\"$client\",job=\"$job\", instance_name=\"$node\"}[$__rate_interval]) * 8",
     "legendFormat": "trans {{device}} "
    }
   ]
  }
 ]
}