{
 "title": "Windows Dashboard",
 "description": "Overview Dashboard for Windows using Prometheus and Windows_Exporter",
 "tags": [ "Windows" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "client",
    "label": "Account",
    "query": {
     "query": "label_values(windows_os_info,client)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(windows_os_info{client=\"$client\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(windows_os_info{client=\"$client\", job=\"$job\"},instance_name)"
    }
   },
   {
    "name": "show_hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(windows_os_info{client=\"$client\", job=\"$job\", instance_name=\"$instance\"},instance_name)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Resource Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Resource Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "time()-windows_system_boot_time_timestamp{job=~\"$job\", client=~\"$client\"}"
    },
    {
     "expr": "windows_cpu_logical_processor{job=~\"$job\", client=~\"$client\"}-0"
    },
    {
     "expr": "avg by (instance_name) (windows_cpu_core_frequency_mhz{job=~\"$job\", client=~\"$client\"})"
    },
    {
     "expr": "100-(avg by (instance_name) (irate(windows_cpu_time_total{job=~\"$job\", client=~\"$client\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100-100 * windows_memory_physical_free_bytes{job=~\"$job\", client=~\"$client\"} / windows_memory_physical_total_bytes{job=~\"$job\", client=~\"$client\"}",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "1-(windows_logical_disk_free_bytes{job=~\"$job\", client=~\"$client\",volume=~\"C:\"}/windows_logical_disk_size_bytes{job=~\"$job\", client=~\"$client\",volume=~\"C:\"})"
    },
    {
     "expr": "(sum(windows_logical_disk_size_bytes{volume!~\"Harddisk.*\"}) by (instance_name) - sum(windows_logical_disk_free_bytes{volume!~\"Harddisk.*\"}) by (instance_name)) / sum(windows_logical_disk_size_bytes{volume!~\"Harddisk.*\"}) by (instance_name) "
    },
    {
     "expr": "windows_system_processes{job=~\"$job\", client=~\"$client\"}"
    },
    {
     "expr": "sum by (instance_name) (windows_service_state{job=~\"$job\", client=~\"$client\",state=\"running\"})"
    }
   ]
  },
  {
   "title": "CPU usage of each host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100-(avg by (instance_name) (irate(windows_cpu_time_total{job=~\"$job\", client=~\"$client\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Memory usage of each host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100.0-100 * windows_memory_physical_free_bytes{job=~\"$job\", client=\"$client\"} / windows_memory_physical_total_bytes{job=~\"$job\", client=\"$client\"}",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "The network details of the maximum traffic network card of each host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "max by (instance_name) (irate(windows_net_bytes_sent_total{client=\"$client\", job=~\"$job\",nic!~'isatap.*|VPN.*'}[2m]))*8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance_name}}_Upload",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "-max by (instance_name) (irate(windows_net_bytes_received_total{client=\"$client\", job=~\"$job\",nic!~'isatap.*|VPN.*'}[2m]))*8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance_name}}_download",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "The maximum disk read and write details of each host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "-max by (instance_name) (irate(windows_logical_disk_read_bytes_total{client=\"$client\", job=\"$job\"}[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance_name}}_Read",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "max by (instance_name) (irate(windows_logical_disk_write_bytes_total{client=\"$client\", job=\"$job\"}[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance_name}}_write",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Details of the maximum disk IO of each host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "-max by (instance_name) (irate(windows_logical_disk_reads_total[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance_name}}_Read",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "max by (instance_name) (irate(windows_logical_disk_writes_total[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance_name}}_write",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Resource details for: $show_hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 16 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - windows_system_boot_time_timestamp {client=\"$client\", job=\"$job\", instance_name=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logical Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 16 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cpu_logical_processor{client=\"$client\", job=\"$job\", instance_name=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 16 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_memory_physical_total_bytes{client=\"$client\", job=\"$job\",instance_name=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-(windows_logical_disk_free_bytes{job=~\"$job\",client=\"$client\", instance_name=~\"$instance\",volume !~\"HarddiskVolume.+\"} / windows_logical_disk_size_bytes{job=~\"$job\",client=\"$client\",instance_name=~\"$instance\",volume !~\"HarddiskVolume.+\"})*100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Number of Processes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_system_processes{client=\"$client\",job=~\"$job\",instance_name=~\"$instance\"}",
     "legendFormat": "Number of Processes"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(windows_net_bytes_total{client=\"$client\", job=\"$job\",instance_name=\"$instance\"}[1m])) > 1)* 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(windows_logical_disk_size_bytes{volume!~\"Harddisk.*\", instance_name=\"$instance\",client=\"$client\", job=\"$job\"}) by (instance_name) - sum(windows_logical_disk_free_bytes{volume!~\"Harddisk.*\", instance_name=\"$instance\", client=\"$client\", job=\"$job\",}) by (instance_name)) / sum(windows_logical_disk_size_bytes{volume!~\"Harddisk.*\", instance_name=\"$instance\", client=\"$client\", job=\"$job\",}) by (instance_name) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage: $show_hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - avg(irate(windows_cpu_time_total{client=\"$client\",job=~\"$job\",instance_name=~\"$instance\",mode=\"idle\"}[5m]))*100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory details: $show_hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_memory_physical_total_bytes{client=\"$client\",job=~\"$job\",instance_name=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Total Physical Memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_memory_physical_free_bytes{client=\"$client\",job=~\"$job\",instance_name=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Total Free Memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "process_virtual_memory_bytes{client=\"$client\",job=~\"$job\",instance_name=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Virtual memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "windows_os_virtual_memory_free_bytes{client=\"$client\",job=~\"$job\",instance_name=~\"$instance\"}",
     "legendFormat": "Free virtual memory"
    }
   ]
  },
  {
   "title": "Disk Usage%: $show_hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_size_bytes{client=\"$client\",job=~\"$job\",instance_name=~\"$instance\",volume!~\"HarddiskVolume.+\"} - windows_logical_disk_free_bytes{client=\"$client\",job=~\"$job\",instance_name=~\"$instance\",volume!~\"HarddiskVolume.+\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Used Space: {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_size_bytes{client=\"$client\",job=~\"$job\",instance_name=~\"$instance\",volume!~\"HarddiskVolume.+\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Total Space: {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_size_bytes{client=\"$client\",job=~\"$job\",instance_name=~\"$instance\",volume!~\"HarddiskVolume.+\"} - windows_logical_disk_free_bytes{client=\"$client\",job=~\"$job\",instance_name=~\"$instance\",volume!~\"HarddiskVolume.+\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Used Space: {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_size_bytes{client=\"$client\",job=~\"$job\",instance_name=~\"$instance\",volume!~\"HarddiskVolume.+\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Total Space: {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Disk Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_read_bytes_total{client=\"$client\",job=~\"$job\",instance_name=~\"$instance\",volume!~\"HarddiskVolume.+\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": " {{volume}} Reads",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_write_bytes_total{client=\"$client\",job=~\"$job\",instance_name=~\"$instance\",volume!~\"HarddiskVolume.+\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{volume}} Writes",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_reads_total{client=\"$client\",job=~\"$job\",instance_name=~\"$instance\",volume!~\"HarddiskVolume.+\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{volume}} Total Reads",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_writes_total{client=\"$client\",job=~\"$job\",instance_name=~\"$instance\",volume!~\"HarddiskVolume.+\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{volume}} Total Writes",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_bytes_sent_total{client=\"$client\",job=~\"$job\",instance_name=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m])*8>0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}}-Sent",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_bytes_received_total{client=\"$client\",job=~\"$job\",instance_name=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m])*8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}}-Received",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "  irate(windows_net_bytes_total{client=\"$client\", job=\"$job\",instance_name=~\"$instance\"}[5m]) / windows_net_current_bandwidth_bytes{instance_name=~\"$instance\"} * 100",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Network discarded/error packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_outbound_discarded_total{client=\"$client\", job=\"$job\",instance_name=~\"$instance\", nic!~\"isatap.+\"}[$__rate_interval]) + irate(windows_net_packets_outbound_errors_total{client=\"$client\", job=\"$job\",instance_name=~\"$instance\"}[$__rate_interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "outbound",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_received_discarded_total{client=\"$client\", job=\"$job\",instance_name=~\"$instance\", nic!~\"isatap.+\"}[$__rate_interval]) + irate(windows_net_packets_received_errors_total{client=\"$client\", job=\"$job\",instance_name=~\"$instance\"}[$__rate_interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "received",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU Load per Procecss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (process) (rate(windows_process_cpu_time_total{client=\"$client\", job=\"$job\",process !~\"Idle\",instance_name=~\"$instance\"}[$__rate_interval]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{procecss}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}